# Generated by Django 5.1.7 on 2025-03-13 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_annual_rainfall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('planted_date', models.DateField()),
                ('last_watered', models.DateField()),
                ('last_fertilized', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('health_status', models.CharField(default='Good', max_length=20)),
                ('growth_stage', models.CharField(default='Seedling', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Watering', 'Watering'), ('Fertilizing', 'Fertilizing'), ('Pruning', 'Pruning'), ('Repotting', 'Repotting'), ('Pest Check', 'Pest Check'), ('Harvesting', 'Harvesting'), ('Other', 'Other')], max_length=20)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_reminders', to=settings.AUTH_USER_MODEL)),
                ('tracked_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='api.trackedplant')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
